"""initial schema with PRD §9 tables

Revision ID: d688256165ff
Revises: 
Create Date: 2026-09-05 16:11:57.764589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd688256165ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_schedule_id', sa.String(), nullable=False),
    sa.Column('schedule_name', sa.String(), nullable=True),
    sa.Column('source_filename', sa.String(), nullable=True),
    sa.Column('source_format', sa.String(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_schedules_external_schedule_id'), 'external_schedules', ['external_schedule_id'], unique=True)
    op.create_index(op.f('ix_external_schedules_id'), 'external_schedules', ['id'], unique=False)
    op.create_table('ingestion_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_sources_code'), 'ingestion_sources', ['code'], unique=True)
    op.create_index(op.f('ix_ingestion_sources_id'), 'ingestion_sources', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM_ADMIN', 'CONTRACTOR_ADMIN', 'PROJECT_CONTROLS', 'DISCIPLINE_PLANNER', 'SITE_SUPERVISOR', name='userrole'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'MATCH', 'APPROVE', 'REJECT', 'CORRECT', 'IMPORT', 'EXPORT', 'LOGIN', 'LOGOUT', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index('ix_audit_logs_project_created', 'audit_logs', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('glossary_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('source_term', sa.String(), nullable=False),
    sa.Column('standardized_term', sa.String(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_mappings_id'), 'glossary_mappings', ['id'], unique=False)
    op.create_index('ix_glossary_mappings_org_term', 'glossary_mappings', ['organization_id', 'source_term'], unique=False)
    op.create_index(op.f('ix_glossary_mappings_organization_id'), 'glossary_mappings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_glossary_mappings_project_id'), 'glossary_mappings', ['project_id'], unique=False)
    op.create_index('ix_glossary_mappings_project_term', 'glossary_mappings', ['project_id', 'source_term'], unique=False)
    op.create_table('productivity_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('discipline', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('planned_quantity', sa.Float(), nullable=True),
    sa.Column('actual_quantity', sa.Float(), nullable=True),
    sa.Column('planned_duration_days', sa.Float(), nullable=True),
    sa.Column('actual_duration_days', sa.Float(), nullable=True),
    sa.Column('productivity_rate', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productivity_benchmarks_discipline'), 'productivity_benchmarks', ['discipline'], unique=False)
    op.create_index(op.f('ix_productivity_benchmarks_id'), 'productivity_benchmarks', ['id'], unique=False)
    op.create_index('ix_productivity_benchmarks_org_disc', 'productivity_benchmarks', ['organization_id', 'discipline'], unique=False)
    op.create_index(op.f('ix_productivity_benchmarks_organization_id'), 'productivity_benchmarks', ['organization_id'], unique=False)
    op.create_index('ix_productivity_benchmarks_project_disc', 'productivity_benchmarks', ['project_id', 'discipline'], unique=False)
    op.create_index(op.f('ix_productivity_benchmarks_project_id'), 'productivity_benchmarks', ['project_id'], unique=False)
    op.create_table('progress_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('activity_reference', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_time', sa.String(), nullable=True),
    sa.Column('discipline', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('equipment_tag', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('ingestion_source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_source_id'], ['ingestion_sources.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_events_id'), 'progress_events', ['id'], unique=False)
    op.create_index(op.f('ix_progress_events_ingestion_source_id'), 'progress_events', ['ingestion_source_id'], unique=False)
    op.create_index('ix_progress_events_org_proj_date', 'progress_events', ['organization_id', 'project_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_progress_events_organization_id'), 'progress_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_progress_events_project_id'), 'progress_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_progress_events_user_id'), 'progress_events', ['user_id'], unique=False)
    op.create_table('schedule_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('activity_code', sa.String(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=False),
    sa.Column('wbs', sa.String(), nullable=False),
    sa.Column('planned_start', sa.Date(), nullable=False),
    sa.Column('planned_finish', sa.Date(), nullable=False),
    sa.Column('is_unplanned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('external_schedule_id', sa.Integer(), nullable=True),
    sa.Column('external_activity_id', sa.String(), nullable=True),
    sa.Column('source_format', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['external_schedule_id'], ['external_schedules.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_activities_activity_code'), 'schedule_activities', ['activity_code'], unique=False)
    op.create_index(op.f('ix_schedule_activities_external_activity_id'), 'schedule_activities', ['external_activity_id'], unique=False)
    op.create_index(op.f('ix_schedule_activities_external_schedule_id'), 'schedule_activities', ['external_schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_activities_id'), 'schedule_activities', ['id'], unique=False)
    op.create_index('ix_schedule_activities_org_proj_code', 'schedule_activities', ['organization_id', 'project_id', 'activity_code'], unique=True)
    op.create_index(op.f('ix_schedule_activities_organization_id'), 'schedule_activities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_schedule_activities_project_id'), 'schedule_activities', ['project_id'], unique=False)
    op.create_table('wbs_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('activity_code', sa.String(), nullable=False),
    sa.Column('activity_name', sa.String(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=False),
    sa.Column('wbs', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=False),
    sa.Column('planned_finish', sa.Date(), nullable=False),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_finish', sa.Date(), nullable=True),
    sa.Column('is_unplanned', sa.Boolean(), nullable=False),
    sa.Column('is_milestone', sa.Boolean(), nullable=False),
    sa.Column('description_vector', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('external_schedule_id', sa.Integer(), nullable=True),
    sa.Column('external_activity_id', sa.String(), nullable=True),
    sa.Column('source_format', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['external_schedule_id'], ['external_schedules.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['wbs_nodes.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wbs_nodes_activity_code'), 'wbs_nodes', ['activity_code'], unique=False)
    op.create_index(op.f('ix_wbs_nodes_external_activity_id'), 'wbs_nodes', ['external_activity_id'], unique=False)
    op.create_index(op.f('ix_wbs_nodes_external_schedule_id'), 'wbs_nodes', ['external_schedule_id'], unique=False)
    op.create_index(op.f('ix_wbs_nodes_id'), 'wbs_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_wbs_nodes_parent_id'), 'wbs_nodes', ['parent_id'], unique=False)
    op.create_index('ix_wbs_nodes_project_code', 'wbs_nodes', ['project_id', 'activity_code'], unique=True)
    op.create_index(op.f('ix_wbs_nodes_project_id'), 'wbs_nodes', ['project_id'], unique=False)
    op.create_index('ix_wbs_nodes_project_wbs', 'wbs_nodes', ['project_id', 'wbs'], unique=False)
    op.create_index(op.f('ix_wbs_nodes_wbs'), 'wbs_nodes', ['wbs'], unique=False)
    op.create_table('audit_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_event_id', sa.Integer(), nullable=False),
    sa.Column('proposed_activity_id', sa.Integer(), nullable=True),
    sa.Column('final_activity_id', sa.Integer(), nullable=True),
    sa.Column('new_activity_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel'), nullable=False),
    sa.Column('decision', sa.Enum('AUTO_MATCH', 'APPROVED', 'CORRECTED', 'REJECTED', 'NEW_ACTIVITY_CREATED', name='decisiontype'), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'PLANNER', name='actortype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['final_activity_id'], ['schedule_activities.id'], ),
    sa.ForeignKeyConstraint(['new_activity_id'], ['schedule_activities.id'], ),
    sa.ForeignKeyConstraint(['progress_event_id'], ['progress_events.id'], ),
    sa.ForeignKeyConstraint(['proposed_activity_id'], ['schedule_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_records_id'), 'audit_records', ['id'], unique=False)
    op.create_index(op.f('ix_audit_records_progress_event_id'), 'audit_records', ['progress_event_id'], unique=False)
    op.create_table('confidence_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_event_id', sa.Integer(), nullable=False),
    sa.Column('proposed_activity_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel'), nullable=False),
    sa.Column('decision', sa.Enum('AUTO_MATCH', 'APPROVED', 'CORRECTED', 'REJECTED', 'NEW_ACTIVITY_CREATED', name='decisiontype'), nullable=False),
    sa.Column('score_gap', sa.Float(), nullable=True),
    sa.Column('exact_identifier_strength', sa.Float(), nullable=True),
    sa.Column('fuzzy_similarity', sa.Float(), nullable=True),
    sa.Column('semantic_similarity', sa.Float(), nullable=True),
    sa.Column('discipline_compatibility', sa.Float(), nullable=True),
    sa.Column('context_compatibility', sa.Float(), nullable=True),
    sa.Column('temporal_compatibility', sa.Float(), nullable=True),
    sa.Column('missing_information_penalty', sa.Float(), nullable=True),
    sa.Column('candidate_ambiguity_penalty', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['progress_event_id'], ['progress_events.id'], ),
    sa.ForeignKeyConstraint(['proposed_activity_id'], ['schedule_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_results_id'), 'confidence_results', ['id'], unique=False)
    op.create_index(op.f('ix_confidence_results_progress_event_id'), 'confidence_results', ['progress_event_id'], unique=False)
    op.create_table('delay_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('wbs_node_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('WEATHER', 'RESOURCE', 'MATERIAL', 'DESIGN', 'PERMIT', 'SUBCONTRACTOR', 'EXTERNAL', 'OTHER', name='delaycategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact_days', sa.Integer(), nullable=False),
    sa.Column('is_critical_path', sa.Boolean(), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wbs_node_id'], ['wbs_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delay_reasons_id'), 'delay_reasons', ['id'], unique=False)
    op.create_index('ix_delay_reasons_project_category', 'delay_reasons', ['project_id', 'category'], unique=False)
    op.create_index(op.f('ix_delay_reasons_project_id'), 'delay_reasons', ['project_id'], unique=False)
    op.create_index(op.f('ix_delay_reasons_wbs_node_id'), 'delay_reasons', ['wbs_node_id'], unique=False)
    op.create_table('event_wbs_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_event_id', sa.Integer(), nullable=False),
    sa.Column('wbs_node_id', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.Enum('EXACT', 'FUZZY', 'SEMANTIC', 'CONTEXTUAL', 'NEW_ACTIVITY', name='matchtype'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('progress_contribution_pct', sa.Float(), nullable=True),
    sa.Column('score_breakdown_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['progress_event_id'], ['progress_events.id'], ),
    sa.ForeignKeyConstraint(['wbs_node_id'], ['wbs_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_wbs_matches_event_node', 'event_wbs_matches', ['progress_event_id', 'wbs_node_id'], unique=False)
    op.create_index(op.f('ix_event_wbs_matches_id'), 'event_wbs_matches', ['id'], unique=False)
    op.create_index(op.f('ix_event_wbs_matches_progress_event_id'), 'event_wbs_matches', ['progress_event_id'], unique=False)
    op.create_index(op.f('ix_event_wbs_matches_wbs_node_id'), 'event_wbs_matches', ['wbs_node_id'], unique=False)
    op.create_table('planner_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('progress_event_id', sa.Integer(), nullable=False),
    sa.Column('proposed_activity_id', sa.Integer(), nullable=True),
    sa.Column('final_activity_id', sa.Integer(), nullable=True),
    sa.Column('new_activity_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'CORRECTED', 'REJECTED', 'NEW_ACTIVITY_CREATED', name='reviewstatus'), nullable=False),
    sa.Column('top_candidates_json', sa.Text(), nullable=True),
    sa.Column('score_breakdown_json', sa.Text(), nullable=True),
    sa.Column('matching_reasons_json', sa.Text(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['final_activity_id'], ['schedule_activities.id'], ),
    sa.ForeignKeyConstraint(['new_activity_id'], ['schedule_activities.id'], ),
    sa.ForeignKeyConstraint(['progress_event_id'], ['progress_events.id'], ),
    sa.ForeignKeyConstraint(['proposed_activity_id'], ['schedule_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planner_reviews_id'), 'planner_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_planner_reviews_progress_event_id'), 'planner_reviews', ['progress_event_id'], unique=False)
    op.create_table('schedule_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_schedule_id', sa.Integer(), nullable=True),
    sa.Column('predecessor_activity_id', sa.Integer(), nullable=False),
    sa.Column('successor_activity_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('lag', sa.Integer(), nullable=False),
    sa.Column('lag_unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['external_schedule_id'], ['external_schedules.id'], ),
    sa.ForeignKeyConstraint(['predecessor_activity_id'], ['schedule_activities.id'], ),
    sa.ForeignKeyConstraint(['successor_activity_id'], ['schedule_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_relationships_external_schedule_id'), 'schedule_relationships', ['external_schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_relationships_id'), 'schedule_relationships', ['id'], unique=False)
    op.create_index('ix_schedule_relationships_pred_succ_type', 'schedule_relationships', ['predecessor_activity_id', 'successor_activity_id', 'relationship_type'], unique=False)
    op.create_index(op.f('ix_schedule_relationships_predecessor_activity_id'), 'schedule_relationships', ['predecessor_activity_id'], unique=False)
    op.create_index(op.f('ix_schedule_relationships_successor_activity_id'), 'schedule_relationships', ['successor_activity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_relationships_successor_activity_id'), table_name='schedule_relationships')
    op.drop_index(op.f('ix_schedule_relationships_predecessor_activity_id'), table_name='schedule_relationships')
    op.drop_index('ix_schedule_relationships_pred_succ_type', table_name='schedule_relationships')
    op.drop_index(op.f('ix_schedule_relationships_id'), table_name='schedule_relationships')
    op.drop_index(op.f('ix_schedule_relationships_external_schedule_id'), table_name='schedule_relationships')
    op.drop_table('schedule_relationships')
    op.drop_index(op.f('ix_planner_reviews_progress_event_id'), table_name='planner_reviews')
    op.drop_index(op.f('ix_planner_reviews_id'), table_name='planner_reviews')
    op.drop_table('planner_reviews')
    op.drop_index(op.f('ix_event_wbs_matches_wbs_node_id'), table_name='event_wbs_matches')
    op.drop_index(op.f('ix_event_wbs_matches_progress_event_id'), table_name='event_wbs_matches')
    op.drop_index(op.f('ix_event_wbs_matches_id'), table_name='event_wbs_matches')
    op.drop_index('ix_event_wbs_matches_event_node', table_name='event_wbs_matches')
    op.drop_table('event_wbs_matches')
    op.drop_index(op.f('ix_delay_reasons_wbs_node_id'), table_name='delay_reasons')
    op.drop_index(op.f('ix_delay_reasons_project_id'), table_name='delay_reasons')
    op.drop_index('ix_delay_reasons_project_category', table_name='delay_reasons')
    op.drop_index(op.f('ix_delay_reasons_id'), table_name='delay_reasons')
    op.drop_table('delay_reasons')
    op.drop_index(op.f('ix_confidence_results_progress_event_id'), table_name='confidence_results')
    op.drop_index(op.f('ix_confidence_results_id'), table_name='confidence_results')
    op.drop_table('confidence_results')
    op.drop_index(op.f('ix_audit_records_progress_event_id'), table_name='audit_records')
    op.drop_index(op.f('ix_audit_records_id'), table_name='audit_records')
    op.drop_table('audit_records')
    op.drop_index(op.f('ix_wbs_nodes_wbs'), table_name='wbs_nodes')
    op.drop_index('ix_wbs_nodes_project_wbs', table_name='wbs_nodes')
    op.drop_index(op.f('ix_wbs_nodes_project_id'), table_name='wbs_nodes')
    op.drop_index('ix_wbs_nodes_project_code', table_name='wbs_nodes')
    op.drop_index(op.f('ix_wbs_nodes_parent_id'), table_name='wbs_nodes')
    op.drop_index(op.f('ix_wbs_nodes_id'), table_name='wbs_nodes')
    op.drop_index(op.f('ix_wbs_nodes_external_schedule_id'), table_name='wbs_nodes')
    op.drop_index(op.f('ix_wbs_nodes_external_activity_id'), table_name='wbs_nodes')
    op.drop_index(op.f('ix_wbs_nodes_activity_code'), table_name='wbs_nodes')
    op.drop_table('wbs_nodes')
    op.drop_index(op.f('ix_schedule_activities_project_id'), table_name='schedule_activities')
    op.drop_index(op.f('ix_schedule_activities_organization_id'), table_name='schedule_activities')
    op.drop_index('ix_schedule_activities_org_proj_code', table_name='schedule_activities')
    op.drop_index(op.f('ix_schedule_activities_id'), table_name='schedule_activities')
    op.drop_index(op.f('ix_schedule_activities_external_schedule_id'), table_name='schedule_activities')
    op.drop_index(op.f('ix_schedule_activities_external_activity_id'), table_name='schedule_activities')
    op.drop_index(op.f('ix_schedule_activities_activity_code'), table_name='schedule_activities')
    op.drop_table('schedule_activities')
    op.drop_index(op.f('ix_progress_events_user_id'), table_name='progress_events')
    op.drop_index(op.f('ix_progress_events_project_id'), table_name='progress_events')
    op.drop_index(op.f('ix_progress_events_organization_id'), table_name='progress_events')
    op.drop_index('ix_progress_events_org_proj_date', table_name='progress_events')
    op.drop_index(op.f('ix_progress_events_ingestion_source_id'), table_name='progress_events')
    op.drop_index(op.f('ix_progress_events_id'), table_name='progress_events')
    op.drop_table('progress_events')
    op.drop_index(op.f('ix_productivity_benchmarks_project_id'), table_name='productivity_benchmarks')
    op.drop_index('ix_productivity_benchmarks_project_disc', table_name='productivity_benchmarks')
    op.drop_index(op.f('ix_productivity_benchmarks_organization_id'), table_name='productivity_benchmarks')
    op.drop_index('ix_productivity_benchmarks_org_disc', table_name='productivity_benchmarks')
    op.drop_index(op.f('ix_productivity_benchmarks_id'), table_name='productivity_benchmarks')
    op.drop_index(op.f('ix_productivity_benchmarks_discipline'), table_name='productivity_benchmarks')
    op.drop_table('productivity_benchmarks')
    op.drop_index('ix_glossary_mappings_project_term', table_name='glossary_mappings')
    op.drop_index(op.f('ix_glossary_mappings_project_id'), table_name='glossary_mappings')
    op.drop_index(op.f('ix_glossary_mappings_organization_id'), table_name='glossary_mappings')
    op.drop_index('ix_glossary_mappings_org_term', table_name='glossary_mappings')
    op.drop_index(op.f('ix_glossary_mappings_id'), table_name='glossary_mappings')
    op.drop_table('glossary_mappings')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_project_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_ingestion_sources_id'), table_name='ingestion_sources')
    op.drop_index(op.f('ix_ingestion_sources_code'), table_name='ingestion_sources')
    op.drop_table('ingestion_sources')
    op.drop_index(op.f('ix_external_schedules_id'), table_name='external_schedules')
    op.drop_index(op.f('ix_external_schedules_external_schedule_id'), table_name='external_schedules')
    op.drop_table('external_schedules')
    # ### end Alembic commands ###
